Added social icons for fellows #11
MLH-Fellowship/prep-portfolio-23.APR.PREP.1 pull request #27
Opened 2023-04-07 16:01 UTC by jessielin34

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

2023-04-07 16:30 UTC, Ankur6702 commented
Hello @akshgpt7 , just wanted to let you know that me and @jessielin34 have resolved issue 11. We created a new social icons div and made some modifications to the CSS. Currently, we haven't updated the fellows.yml file to link it to the actual social links of all the fellows. We are planning to update this file at the very end because in other issues there are significant changes in this file made by other fellows. 
Could you please review our changes? 
Thank you!

2023-04-07 17:52 UTC, akshgpt7 requested changes
Thanks for working on this. The icons look awesome!
Can you just:
1. Fix the merge conflict that has come up
2. Remove the files that are not needed (see my review comments)

It'll be ready to merge it after that

2023-04-07 17:52 UTC, akshgpt7 commented on Gemfile.lock
> +    liquid (4.0.4)
You don't need to commit the Gemfile.lock. Can you omit this file please?

2023-04-07 17:52 UTC, akshgpt7 commented on bin/bundle
> +#!/usr/bin/env ruby
Don't need any of the files in the `bin/` directory. Please remove these files too.

2023-04-07 19:09 UTC, Ankur6702 commented
Hey @akshgpt7 , thanks for reviewing our PR. We have updated the PR as per the suggestions given by you. You can look into it now. Let me know if any change is still required from our end!
Thanks

2023-04-10 17:00 UTC, akshgpt7 commented
Hey, can you fix the merge conflicts, will be good to merge then!

2023-04-10 17:01 UTC, akshgpt7 commented
Also mention the issue number in the PR description that it fixes.
"Fixes #x"

2023-04-10 18:54 UTC, Ankur6702 commented
Fixes #11 
@akshgpt7 I've resolved the merge conflicts. Please let me know if its ready to be merged or not!

2023-04-10 19:00 UTC, akshgpt7 commented
You need to add "Fixes #11" to the PR description, not as a comment.

2023-04-10 19:01 UTC, akshgpt7 commented
LGTM, Thanks for working on this!

2023-04-10 19:01 UTC, merged